config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # resources :spaces, only: [:index, :new, :create, :show] do
  #   resources :bookings, only: [:index, :new, :create, :show]
  # end

  # resources :bookings do
  #   resources :payments, only: :new
  # end

  resource :user, only: [] do
    # this will route /user/bookings to Users::BookingsController
    resources :bookings, only: [:index], module: :users
  end

  resources :spaces, only: [:index, :new, :create, :show] do
    # shallow: true will prevent the member routes from being nested
    # it will also prevent resources :payments from being nested in `/spaces/`
    resources :bookings, shallow: true do
      resources :payments, only: :new, shallow: true do
        collection do
         get :success
        end
      end
    end
  end


  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'list', to: 'pages#list'
  get 'privacy', to: 'pages#privacy'

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/space.rb
class Space < ApplicationRecord
  validates :address, presence: true, uniqueness: true
  validates :city, presence: true
  validates :postcode, presence: true
  validates :number_of_people, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  monetize :price_cents

  mount_uploader :photo, PhotoUploader

  # delete all the bookings when a space is deleted
  has_many :bookings, dependent: :destroy

  def full_address
    [address, city, postcode].compact.join(',')
  end

  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @spaces = Space.geocoded
    session[:query1] = params[:query1]
    session[:query2] = params[:query2]
    session[:location] = params[:location]

    if params[:location].present?
      @spaces = @spaces.where(city: params[:location])
    end

    if params[:query1].present? && params[:query2].present?
      from = DateTime.parse(params[:query1])
      to = DateTime.parse(params[:query2])



      @spaces = @spaces.where.not(
      id: Booking.where(state: 'paid').select(:space_id).overlapping(from, to)
      ).geocoded

    end

    @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space: space })
      }
    end
  end

  def show
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  private

  def space_params
    params.require(:space).permit(:address, :city, :postcode, :number_of_people, :daily_price, :description, :photo)
  end
end

app/views/spaces/_info_window.html.erb
<%= cl_image_tag space.photo, class: "info-window-img" %>

<div class="info-window-details">
  <h6><%= space.address %></h6>
  <p><%= space.city %></p>
  <div class="flex space-between align-items-center">
  <p><%= space.postcode %></p>
  <p><%= humanized_money_with_symbol(space.price) %></p>
  </div>
  <a href="/spaces/<%= space.id %>/bookings/new" class="stretched-link"></a>
</div>

app/views/spaces/index.html.erb
<div class="mt-2 mb-2">
  <div class="d-none d-md-block filters m-l-26 m-r-26">
  <%= form_tag spaces_path, method: :get, class: "form-inline" do %>
  <%= label_tag :location, "City"%>
  <%= select_tag :location, options_for_select(["London", "Bath", "Brighton", "Bristol", "Cambridge" ], params[:location]), class: "form-control ml-2 mr-4" %>
  <%= label_tag :query1, "Check in" %>
  <%= date_field_tag :query1,
  params[:query1], class: "form-control ml-2 mr-4" %>
  <%= label_tag :query2, "Check out" %>
  <%= date_field_tag :query2,
  params[:query2], class: "form-control ml-2 mr-2" %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  </div>

  <div class="d-block d-md-none filters m-l-26 m-r-26">
  <%= form_tag spaces_path, method: :get, class: "form-inline" do %>
  <%= label_tag :location, "City"%>
  <%= select_tag :location, options_for_select(["London", "Bath", "Brighton", "Bristol", "Cambridge" ], params[:location]), class: "form-control mb-2" %>
  <%= label_tag :query1, "Check in" %>
  <%= date_field_tag :query1,
  params[:query1], class: "form-control mb-2" %>
  <%= label_tag :query2, "Check out" %>
  <%= date_field_tag :query2,
  params[:query2], class: "form-control mb-2" %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>




<div class="main-container">

  <div class="row">

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7 cards">
      <% @spaces.each do |space| %>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5">
            <%= cl_image_tag space.photo, class: "card-img" %>
          </div>

          <div class="col-xs-8 col-sm-8 col-md-12 col-lg-7">
            <div class="card-body">
              <h5 class="card-title"><%= space.address %></h5>
              <p class="card-text"><%= space.description.split[0..25].join(' ') %>...</p>

              <div class="card-details flex justify-content-space-between">
                <p class="card-text"><%= space.postcode %></p>
                <p class="card-text">Daily price: <%= humanized_money_with_symbol(space.price) %></p>
              </div>
            </div>
          </div>
        </div>
        <p class="card-text"><%= link_to "", new_space_booking_path(space), class: "stretched-link details" %></p>
      </div>
      <% end %>
    </div>

    <div class="d-none d-md-block col-lg-5" id="map" data-markers="<%=
    @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  </div>



</div>

app/views/spaces/new.html.erb
<h2 class="m-t-10 m-l-15">List a Space</h2>

<div class="page-wrapper">


  <div class="page-content">
  <%= simple_form_for @space do |f| %>
    <%= f.input :address, error: "address can't be blank" %>
    <%= f.input :city, error: "city can't be blank" %>
    <%= f.input :postcode, error: "postcode can't be blank" %>
    <%= f.input :number_of_people, error: "number of people can't be blank" %>
    <%= f.input :price_cents, error: "daily price can't be blank" %>
    <%= f.input :description, error: "description can't be blank" %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-primary btn-lg btn-block m-b-15" %>
  <% end %>
</div>

</div>

app/views/spaces/show.html.erb
<div class="container">

  <h2 class="bold m-t-30 m-b-20"><%= @space.address %></h2>
  <div class="row justify-content-center">

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
      <div class="img-show" style="background-image: url(<%= @space.photo %>)"></div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
      <div class="reservation-form p-l-20 p-r-20 justify-content-center">
        <h5 class="bold m-t-30 m-b-30"><%= @space.address %></h5>

        <%= form_with(model: [@space, @booking], local: true) do |f| %>
        <%= label_tag :check_in, "Check in" %>
        <%= f.date_field :check_in, value: @query1, class: "form-control" %>
        <%= label_tag :check_out, "Check out", class: "m-t-25" %>
        <%= f.date_field :check_out, value: @query2, class: "form-control" %>

        <%= submit_tag "Reserve", class: "btn btn-primary btn-lg btn-block m-t-20 m-b-30" %>
        <% end %>

      </div>
    </div>

  </div>
  <div class="space-details m-t-30">
    <p><%= @space.description %></p>
    <div class="flex justify-content-space-between">
      <p class="m-t-20"><%= @space.address %>, <%= @space.city %>, <%= @space.postcode %></p>
      <!-- <p class=" bold m-t-20"><%= @space.number_of_people %> People</p> -->
      <p class="bold m-t-20 m-b-30">Daily price: <%= humanized_money_with_symbol(@space.price) %></p>
    </div>
  </div>

</div>