config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # resources :spaces, only: [:index, :new, :create, :show] do
  #   resources :bookings, only: [:index, :new, :create, :show]
  # end

  # resources :bookings do
  #   resources :payments, only: :new
  # end

  resource :user, only: [] do
    # this will route /user/bookings to Users::BookingsController
    resources :bookings, only: [:index], module: :users
  end

  resources :spaces, only: [:index, :new, :create, :show] do
    # shallow: true will prevent the member routes from being nested
    # it will also prevent resources :payments from being nested in `/spaces/`
    resources :bookings, shallow: true do
      resources :payments, only: :new, shallow: true do
        collection do
         get :success
        end
      end
    end
  end


  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'list', to: 'pages#list'
  get 'privacy', to: 'pages#privacy'

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer p-t-30">
  <div class="row">
    <div class="col-md-3 footer-logo">
      <h5 class="bold p-l-15" >Workspace</h5>
    </div>

    <div class="col-md-2 m-l-15 footer-discover">
      <p class="bold" >Discover Workspace</p>
      <a href="/about" class=""><p>About us</p></a>
      <a id="link-how-it-works" href="/#how-it-works"><p>How it works</p></a>
      <a id="link-new-spaces" href="/#best-spaces"><p>New spaces</p></a>
      <p class="b5b5b5">Contact us</p>
    </div>

    <div class="col-md-2 m-l-15 footer-partnership">
      <p class="bold" >Partnership</p>
      <a href="/list"><p>List a space</p></a>
      <p class="b5b5b5">Why join us</p>
      <p class="b5b5b5">FAQ partners</p>
    </div>

    <div class="col-md-2 m-l-15 footer-legal">
      <p class="bold" >Legal</p>
      <p class="b5b5b5">Terms & Conditions</p>
      <a href="/privacy" ><p>Privacy Policy</p></a>
      <p class="b5b5b5">Cookie Policy</p>
    </div>

    <div class="col-md-2 m-l-15 footer-follow-us">
      <div class="footer-links flex p-r-5">
        <a href="#" class="disabled"><i class="fab fa-facebook-f"></i></a>
        <a href="#" class="disabled"><i class="fab fa-instagram"></i></a>
        <a href="#" class="disabled"><i class="fab fa-twitter"></i></a>
        <a href="#" class="disabled"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>
  </div>

  <div class="footer-copyright p-b-5 p-r-5" align="right">
    This page is made with <i class="fas fa-heart"></i> in quarantine.
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to "Workspace", root_path, class: "navbar-brand" %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto m-l-10">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List with Us", list_path, class: "nav-link" %>
        </li>
          <li class="nav-item">
          <%= link_to "Your Booking", user_bookings_path, class: "nav-link d-block d-sm-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link d-block d-sm-none" %>
        </li>
        <li class="nav-item dropdown">

          <a class="btn d-none d-sm-block" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Your Bookings", user_bookings_path, class: "dropdown-item light-grey" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item light-grey" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List with Us", list_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "Workspace", root_path, class: "navbar-brand-searchbar" %>

  <input type="search" class="form-control ds-input searchbar bg-light d-none d-sm-block" id="search-input" placeholder= "Search..." aria-label="Search for..." autocomplete="off" data-docs-version="4.4" spellcheck="false" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-owns="algolia-autocomplete-listbox-0" dir="auto" style="position: relative; vertical-align: top;">

  <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
  </form> -->


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto m-l-10">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "About", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List with Us", new_space_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Your Booking", my_reservations_bookings_path, class: "nav-link d-block d-sm-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link d-block d-sm-none" %>
        </li>
        <li class="nav-item dropdown">

          <a class="btn d-none d-sm-block" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Your Bookings", my_reservations_bookings_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List with Us", new_space_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>


  <input type="search" class="form-control ds-input searchbar bg-light d-block d-sm-none m-t-10" id="search-input" placeholder= "Search..." aria-label="Search for..." autocomplete="off" data-docs-version="4.4" spellcheck="false" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-owns="algolia-autocomplete-listbox-0" dir="auto" style="position: relative; vertical-align: top;">
</div>